#!/bin/ksh

javac --module-path ../../lib/javafx-sdk-22.0.1 --add-modules javafx.controls graphics.java

if [ $? -eq 0 ]; then
	java --module-path ../../lib/javafx-sdk-22.0.1 --add-modules javafx.controls graphics
else
	echo "[$0] ERROR: Return value of javac not 0!"
fi
